# Generated by Django 4.1.7 on 2023-04-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LykaApp', '0006_device_price_alter_devicefeatures_devicename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=250)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cartlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaCart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaApp.device')),
            ],
        ),
    ]
