# Generated by Django 4.1.7 on 2023-04-19 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LykaCart', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 4, 19)),
        ),
    ]
