# Generated by Django 4.1.7 on 2023-04-17 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LykaApp', '0006_device_price_alter_devicefeatures_devicename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingName', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('deliverydate', models.DateField(verbose_name=django.utils.timezone.now)),
                ('deliveryaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaApp.device')),
            ],
        ),
    ]
