# Generated by Django 4.1.7 on 2023-04-17 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LykaOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deliverydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
