# Generated by Django 4.1.7 on 2023-04-17 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LykaApp', '0006_device_price_alter_devicefeatures_devicename_and_more'),
        ('LykaOrders', '0002_alter_orders_deliverydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=255)),
                ('placeddate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('deliverydate', models.DateField(default=django.utils.timezone.now)),
                ('deliveryaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.address')),
                ('orderlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaApp.device')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
