# Generated by Django 4.1.7 on 2023-04-18 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LykaApp', '0006_device_price_alter_devicefeatures_devicename_and_more'),
        ('LykaOrders', '0003_order_orderdetails_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryaddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deliverydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='LykaApp.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
