# Generated by Django 4.1.7 on 2023-04-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaAccounts', '0006_remove_customer_defaultaddress'),
        ('LykaOrders', '0005_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='owner_of_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LykaAccounts.customer'),
        ),
    ]
