# Generated by Django 4.1.7 on 2023-04-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaApp', '0006_device_price_alter_devicefeatures_devicename_and_more'),
        ('LykaOrders', '0006_address_owner_of_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaApp.device')),
            ],
        ),
    ]
