# Generated by Django 4.1.7 on 2023-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LykaOrders', '0007_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalitems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
