# Generated by Django 4.1.7 on 2023-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LykaOrders', '0008_order_totalitems_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Placed', max_length=255),
        ),
    ]
