# Generated by Django 4.1.7 on 2023-04-19 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LykaOrders', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverydate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
