# Generated by Django 4.1.7 on 2023-04-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaOrders', '0003_order_orderdetails_delete_orders'),
        ('LykaAccounts', '0003_alter_customer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.order'),
        ),
    ]
