# Generated by Django 4.1.7 on 2023-04-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaOrders', '0003_order_orderdetails_delete_orders'),
        ('LykaAccounts', '0004_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='defaultaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LykaOrders.address'),
        ),
    ]
