# Generated by Django 4.1.7 on 2023-04-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaAccounts', '0006_remove_customer_defaultaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upiId', models.CharField(max_length=50)),
                ('upiOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaAccounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=50)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('cvv', models.IntegerField()),
                ('cardType', models.CharField(max_length=50)),
                ('cardOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaAccounts.customer')),
            ],
        ),
    ]
