# Generated by Django 4.1.7 on 2023-04-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LykaAccounts', '0007_upipaymentdetails_cardpaymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpaymentdetails',
            name='cvv',
        ),
    ]
