# Generated by Django 4.1.7 on 2023-04-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaAccounts', '0008_remove_cardpaymentdetails_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpaymentdetails',
            name='cardOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LykaAccounts.customer'),
        ),
    ]
