# Generated by Django 4.1.7 on 2023-04-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LykaAccounts', '0010_alter_upipaymentdetails_upiowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
    ]
