# Generated by Django 4.1.7 on 2023-04-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LykaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='catergory',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='features',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
