# Generated by Django 4.1.7 on 2023-04-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LykaApp', '0002_remove_features_product_ptr_remove_images_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=100, unique=True)),
                ('slugModel', models.SlugField(max_length=100, unique=True)),
                ('stock', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('desc', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaApp.cate')),
            ],
        ),
        migrations.CreateModel(
            name='deviceFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=100)),
                ('battery', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('processor', models.CharField(max_length=100)),
                ('deviceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LykaApp.device')),
            ],
        ),
    ]
