# Generated by Django 4.1.7 on 2023-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LykaApp', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imgname',
            field=models.CharField(default='q', max_length=50),
            preserve_default=False,
        ),
    ]
