# Generated by Django 4.1.7 on 2023-04-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LykaApp', '0005_image_imgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicefeatures',
            name='deviceName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='LykaApp.device'),
        ),
        migrations.AlterField(
            model_name='image',
            name='DeviceName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='LykaApp.device'),
        ),
    ]
